name: EachWorld
main: takesi\main
version: 2.2
api: [5.0.0]
load: POSTWORLD
author: takesi
commands:
  do:
    description: "実行コマンド"
    usage: /do
    permission: eachworld-fork.do
  wo:
    description: "Worldコマンド"
    usage: /wo <subcommand>
    permission: eachworld-fork.wo

permissions:
  eachworld-fork.do:
    default: true
  eachworld-fork.wo:
    default: true